# Generated by Django 5.1.3 on 2024-11-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_books_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
